version: '2'

services:
  db:
    hostname: mysql.urlchecker.local
    build:
      context: ..
      dockerfile: ./deployments/mysql/Dockerfile
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=work
    - MYSQL_USER=checker
    - MYSQL_PASSWORD=checker
    ports: 
      - 3306:3306
    networks:
      static-network:
        ipv4_address: 172.20.0.2

  api:
    hostname: api.urlchecker.local
    build:
      context: ..
      dockerfile: ./deployments/api/Dockerfile
    ports: 
      - 443:443
    networks:
      static-network:
        ipv4_address: 172.20.0.3
    environment:
    - DB_HOST=172.20.0.2
    - DB_PORT=3306
    - DB_SCHEMA=work
    - DB_USER=checker
    - DB_PASSWORD=checker
    - DB_DROP=false
    depends_on:
      - db
    tty: true

  disp:
    hostname: disp.urlchecker.local
    build:
      context: ..
      dockerfile: ./deployments/disp/Dockerfile
    networks:
      static-network:
        ipv4_address: 172.20.0.4
    environment:
    - DB_HOST=172.20.0.2
    - DB_PORT=3306
    - DB_SCHEMA=work
    - DB_USER=checker
    - DB_PASSWORD=checker
    - URL_CONFIG=url.json
    - HCK_DURATION=1
    depends_on:
      - api
    tty: true

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16

